name: Selenium with ZAP Security Testing

on:
  push:
    branches:
      - master  # Change to your main branch name
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Install OWASP Zap
      run: |
        sudo apt-get update
        docker pull zaproxy/zap-stable
        
    - name: Run OWASP ZAP Docker container
      run: |
        docker run -d --name zap -v $(pwd):/zap/wrk/:rw -u zap -p 8080:8080 -i zaproxy/zap-stable zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=fird1714cemk320pcfga1oun5e
        ls
        docker exec -t zap /bin/bash
        ls
        cd wrk
        ls
        mvn test -Dtest=SeleniumZap.java
      
#    - name: Run TestNG test
#      run: |
#

    - name: Upload Reports
      uses: actions/upload-artifact@v2
      with:
        name: zap-reports
        path: /zap/wrk/go-1%-dashboard.html
